pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('Front-end') {
  agent {
    docker { image 'openjdk:17-jdk' }
  }
  steps {
    sh 'echo "public class HelloWorld { public static void main(String[] args) { System.out.println(\\"Hello, World!\\"); } }" > HelloWorld.java && javac HelloWorld.java && java HelloWorld'
  }
}
      }
    }

